before_install:
  - sudo apt-get install libgif-dev
language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
  - staging
  - dev
script:
  - npm test
  - npm run build
