before_install:
- sudo apt-get install libgif-dev
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - staging
  - dev
script:
- npm run lint
- npm run test
- npm run build
before_deploy:
- npm run release
deploy:
  skip_cleanup: true  
  provider: npm
  email: sebastien.tasson@gmail.com
  api_key:
    secure: Vgwn5a5bM9qcBkQnEcmFXfCe3Yeckl+slJ2Bmj2ogsDrchPkUqf92rODgAnjV6Z/1SgMMHqak9MEhPXlDipmLXf1F9wCH/j3OCWhISNrh39CScFHI7FUwVWFEMj+laYMf+Xr7oPG8a6z+XLPCoPpX7Muw5L08pl1Dmc61IQ38L29Jmsfqy4Iizv/SRnCwoP7shklw0LeGbnoLiADFbVt7v497Nzx3ZdAx9nuKZMRigrLzctoJHQo6Xptk5Ut8Rp/S/X37ha6Hj8bLCpdw5pO3Q7VY0TjDyyNixZQKGr+BS1b6xnPksvD0sGig0YXn+vPv/F65GoHa6DH75QMsHCG3dGyFzWxaeiPCCKlVJFiLkrTfR1yWvmw5KLXrLdm4Wv92LrPgL2YPK3pfR4Miqj/dFcE+KkatKB/bBXj5Mv1Aid2wyLkSJUqg05u3GFxRlFq2+w6SH9ORzPzYPDTFpSWDH8qVtPEnypeiCU/jJjsaBrRg/vErsg3xVVQ+4F9WWPbAju/MU2yZ1RzcINvA6FojJCPin86wxS8nWNIE9I1TC62Pp3Xj6YmSH/qiFB2J1rPeJ9jpivI3uN1UrucoPBSQaNWKgsRPc+Y9lULeAMkcCIX8DdCVf9fWjyxy7P/s/f02kAC8MgBaeZIridl1qf7+tI2IUKgmAR9UJw/38YnhpQ=
  on:
    repo: stasson/vue-mdc-adapter
    branch: staging
after_deploy:
- git push --follow-tags origin staging 
- git push origin master